Math Magicians: tests
pountzas/math-magicians-react pull request #6
Opened 2021-08-25 22:18 UTC by brenoxav

## Math Magicians: tests

- Write unit tests with React Testing Library
- Write unit tests with snapshots with Jest
- Write unit tests for the files operate.js and calculate.js using Jest
- Create unit tests for all React components
- Use Jest snapshots to test the components
- Use React Testing Library to simulate user interaction
- All tests should pass

2021-08-25 23:17 UTC, bellom requested changes
## Hi @brenoxav @pountzas  👏 , 

### Awesome job so far!! :+1: 

#### You have done wonderfully well writing unit test and jest snapshot for all the component setting up linter, and also good commit messages 🔥, However, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Required Changes! ♻️ 

_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 23:17 UTC, bellom commented on src/logic/__tests__/calculate.test.js
> +  test('it sould return a null object when AC button is used', () => {
### [Optional]
kindly correct the typo `should` not `sould`

2021-08-25 23:17 UTC, bellom commented on src/logic/__tests__/calculate.test.js
> +  });
We need to write a unit test for all the functionalities & scenarios in `calculate.js` module.

kindly add unit test for the following case `buttonName === '+/-'`

2021-08-26 15:07 UTC, henatan99 commented on src/logic/__tests__/calculate.test.js
> +  test('it sould return a null object when AC button is used', () => {
- This issue is resolved. Well done! :+1:

2021-08-26 15:10 UTC, henatan99 commented on src/logic/__tests__/calculate.test.js
> +  });
- This issue is well addressed! :clap: :clap:

2021-08-26 15:12 UTC, henatan99 approved these changes
Hi @pountzas && @brenoxav , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-26 15:16 UTC, merged